# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: greet
# "service" is the name of this project. This will also be added to your AWS resource names.
service: greet

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2
  environment:
    CLIENT_ID: ${ssm:/Client_ID} # securely fetch from

functions:

  signUp:
    handler: handlers/signUp.signUp
    events:
      - httpApi:
          path: /signUp
          method: post
  ConfirmSignUp:
    handler: handlers/confirmSignUp.ConfirmSignUp
    events:
      - httpApi:
          path: /confirmSignUp
          method: post
  signIn:
    handler: handlers/signin.signIn
    events:
      - httpApi:
          path: /sign-in
          method: post

    
